import { DataType } from "../map/map-wrapper.types";

export const dataMock: Record<DataType, any> = {
  ip: "212.77.98.9",
  type: "ipv4",
  continent_code: "EU",
  continent_name: "Europe",
  country_code: "PL",
  country_name: "Poland",
  region_code: "PM",
  region_name: "Pomerania",
  city: "Gda\u0144sk",
  zip: "80-009",
  latitude: 54.31930923461914,
  longitude: 18.63736915588379,
  location: {
    geoname_id: 3099434,
    capital: "Warsaw",
    languages: [{ code: "pl", name: "Polish", native: "Polski" }],
    country_flag: "https://assets.ipstack.com/flags/pl.svg",
    country_flag_emoji: "\ud83c\uddf5\ud83c\uddf1",
    country_flag_emoji_unicode: "U+1F1F5 U+1F1F1",
    calling_code: "48",
    is_eu: true,
  },
  time_zone: {
    id: "Europe/Warsaw",
    current_time: "2022-08-28T12:31:36+02:00",
    gmt_offset: 7200,
    code: "CEST",
    is_daylight_saving: true,
  },
  currency: {
    code: "PLN",
    name: "Polish Zloty",
    plural: "Polish zlotys",
    symbol: "z\u0142",
    symbol_native: "z\u0142",
  },
  connection: { asn: 12827, isp: "Wirtualna Polska Media s.A." },
};
